services:
  - type: web
    name: omegle-clone
    env: python
    # Ensure dependencies are installed
    buildCommand: "pip install -r requirements.txt"
    # Use the asynchronous eventlet worker for SocketIO
    startCommand: "gunicorn app:app --worker-class eventlet -b 0.0.0.0:$PORT"
