services:
  - type: web
    name: omegle-clone
    env: python
    region: oregon
    pythonVersion: 3.13.4
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python3 app.py"
    plan: free
